### ISSUE TITLE
SubPage macro isn't working with Trac 1.2.3

### ISSUE THREAD

**Issue by u8813345** [trac-hacks/TracSubPages#4]
Hi,
 I am a subpage macro user.
 after I upgrade  my trac system to v1.2.3
 I find TracSubpages is not working anymore.
 

```
Error: Macro subpage(ProjectBmcSchedule,true) failed
Environment' object has no attribute 'get_db_cnx'
```

I find something on trac web site. 
_The use of env.get_db_cnx() is now deprecated._ please click [here](https://trac.edgewall.org/wiki/TracDev/DatabaseApi) to know more.

```
Trac 1.2.3
Integrated SCM, wiki, issue tracker and project environment
TracSubPages 0.5
A Trac macro that displays the bodies of wiki pages inside other wiki pages
```

**Comment by rjollos** [comment]
[IncludeMacro](http://trac-hacks.org/wiki/IncludeMacro) is probably a better macro.
